/**
 * Regenerate the autogenerated block in `docs/reference/cli.md` from the live commander
 * definition. Run via `pnpm docs:gen-cli`.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { buildProgram } from '../../src/cli.js';

const dirname = fileURLToPath(new URL('.', import.meta.url));
const refFile = path.join(dirname, '..', 'reference', 'cli.md');

const program = buildProgram();
const rootHelp = program.helpInformation();
const subHelp = program.commands
  .filter((c) => c.name() !== 'help')
  .map((c) => `### \`ghaar ${c.name()}\`\n\n\`\`\`\n${c.helpInformation().trim()}\n\`\`\``)
  .join('\n\n');

const content = await readFile(refFile, 'utf8');
const block = [
  '<!-- AUTOGEN:BEGIN -->',
  '',
  '## Top-level',
  '',
  '```',
  rootHelp.trim(),
  '```',
  '',
  '## Subcommands',
  '',
  subHelp,
  '',
  '<!-- AUTOGEN:END -->',
].join('\n');

const updated = content.replace(/<!-- AUTOGEN:BEGIN -->[\s\S]*?<!-- AUTOGEN:END -->/, block);

await writeFile(refFile, updated, 'utf8');
process.stdout.write(`Wrote ${refFile}\n`);
